apply plugin: 'com.android.application'

android {
    namespace 'com.sajottionusaraga.treasureisland.android'
    compileSdk 34

    defaultConfig {
        applicationId 'com.sajottionusaraga.treasureisland.android'
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName '1.0'
    }

    sourceSets {
        main.java.srcDirs = ['src/main/java']
        main.res.srcDirs = ['src/main/res']
        main.assets.srcDirs = ['assets']
    }

    packagingOptions {
        exclude 'META-INF/robovm/ios/robovm.xml'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}

dependencies {
    implementation project(':core')
    implementation "com.badlogicgames.gdx:gdx-backend-android:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-armeabi-v7a"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-arm64-v8a"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86"
    implementation "com.badlogicgames.gdx:gdx-platform:$gdxVersion:natives-x86_64"
}
